// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package networkproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MessageType possibilities include but are not limited to :
//  "connrequest"
//  "connChallenge"
//  "challengeAnswer"
//  "ACK"
//  "NACK"
//  "EOF"
type FILEINFOS struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Location             string   `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FILEINFOS) Reset()         { *m = FILEINFOS{} }
func (m *FILEINFOS) String() string { return proto.CompactTextString(m) }
func (*FILEINFOS) ProtoMessage()    {}
func (*FILEINFOS) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_00401d7bc443db53, []int{0}
}
func (m *FILEINFOS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FILEINFOS.Unmarshal(m, b)
}
func (m *FILEINFOS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FILEINFOS.Marshal(b, m, deterministic)
}
func (dst *FILEINFOS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FILEINFOS.Merge(dst, src)
}
func (m *FILEINFOS) XXX_Size() int {
	return xxx_messageInfo_FILEINFOS.Size(m)
}
func (m *FILEINFOS) XXX_DiscardUnknown() {
	xxx_messageInfo_FILEINFOS.DiscardUnknown(m)
}

var xxx_messageInfo_FILEINFOS proto.InternalMessageInfo

func (m *FILEINFOS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FILEINFOS) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FILEINFOS) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type ACKNACK struct {
	MessageType          string   `protobuf:"bytes,1,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	ACK                  uint64   `protobuf:"varint,2,opt,name=ACK,proto3" json:"ACK,omitempty"`
	NACKs                []uint64 `protobuf:"varint,3,rep,packed,name=NACKs,proto3" json:"NACKs,omitempty"`
	Hash                 []byte   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	ToDecrypt            []byte   `protobuf:"bytes,5,opt,name=ToDecrypt,proto3" json:"ToDecrypt,omitempty"`
	KeyToUse             string   `protobuf:"bytes,6,opt,name=keyToUse,proto3" json:"keyToUse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACKNACK) Reset()         { *m = ACKNACK{} }
func (m *ACKNACK) String() string { return proto.CompactTextString(m) }
func (*ACKNACK) ProtoMessage()    {}
func (*ACKNACK) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_00401d7bc443db53, []int{1}
}
func (m *ACKNACK) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACKNACK.Unmarshal(m, b)
}
func (m *ACKNACK) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACKNACK.Marshal(b, m, deterministic)
}
func (dst *ACKNACK) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACKNACK.Merge(dst, src)
}
func (m *ACKNACK) XXX_Size() int {
	return xxx_messageInfo_ACKNACK.Size(m)
}
func (m *ACKNACK) XXX_DiscardUnknown() {
	xxx_messageInfo_ACKNACK.DiscardUnknown(m)
}

var xxx_messageInfo_ACKNACK proto.InternalMessageInfo

func (m *ACKNACK) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *ACKNACK) GetACK() uint64 {
	if m != nil {
		return m.ACK
	}
	return 0
}

func (m *ACKNACK) GetNACKs() []uint64 {
	if m != nil {
		return m.NACKs
	}
	return nil
}

func (m *ACKNACK) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ACKNACK) GetToDecrypt() []byte {
	if m != nil {
		return m.ToDecrypt
	}
	return nil
}

func (m *ACKNACK) GetKeyToUse() string {
	if m != nil {
		return m.KeyToUse
	}
	return ""
}

func init() {
	proto.RegisterType((*FILEINFOS)(nil), "networkproto.FILEINFOS")
	proto.RegisterType((*ACKNACK)(nil), "networkproto.ACKNACK")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_00401d7bc443db53) }

var fileDescriptor_rpc_00401d7bc443db53 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc9, 0x4b, 0x2d, 0x29, 0xcf, 0x2f, 0xca, 0x06, 0xf3,
	0x94, 0xfc, 0xb9, 0x38, 0xdd, 0x3c, 0x7d, 0x5c, 0x3d, 0xfd, 0xdc, 0xfc, 0x83, 0x85, 0x84, 0xb8,
	0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58,
	0x71, 0x66, 0x55, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x4b, 0x10, 0x98, 0x2d, 0x24, 0xc5, 0xc5,
	0x91, 0x93, 0x9f, 0x9c, 0x58, 0x92, 0x99, 0x9f, 0x27, 0xc1, 0x0c, 0x56, 0x0b, 0xe7, 0x2b, 0x2d,
	0x64, 0xe4, 0x62, 0x77, 0x74, 0xf6, 0xf6, 0x73, 0x74, 0xf6, 0x16, 0x52, 0xe0, 0xe2, 0xf6, 0x4d,
	0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d, 0xa9, 0x2c, 0x80, 0x19, 0x8b, 0x2c, 0x24, 0x24, 0xc0, 0xc5,
	0xec, 0xe8, 0xec, 0x0d, 0x35, 0x1c, 0xc4, 0x14, 0x12, 0xe1, 0x62, 0x05, 0xe9, 0x2d, 0x96, 0x60,
	0x56, 0x60, 0xd6, 0x60, 0x09, 0x82, 0x70, 0x40, 0xae, 0xf0, 0x48, 0x2c, 0xce, 0x90, 0x60, 0x51,
	0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x85, 0x64, 0xb8, 0x38, 0x43, 0xf2, 0x5d, 0x52, 0x93, 0x8b,
	0x2a, 0x0b, 0x4a, 0x24, 0x58, 0xc1, 0x12, 0x08, 0x01, 0x90, 0x1b, 0xb3, 0x53, 0x2b, 0x43, 0xf2,
	0x43, 0x8b, 0x53, 0x25, 0xd8, 0x20, 0x6e, 0x84, 0xf1, 0x93, 0xd8, 0xc0, 0x7e, 0x37, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x02, 0xf1, 0x98, 0x56, 0x16, 0x01, 0x00, 0x00,
}
